### ISSUE TITLE
vim tmux configuration

### ISSUE THREAD

**Issue by hududed** [jecaro/dotfiles#1]
cant get the switching between panes with h j k l to work, Is it working on yours?

After some digging, there may be some [workaround](https://github.com/christoomey/vim-tmux-navigator/issues/295)

Could you work that in?

**Comment by jecaro** [comment]
It's working fine in my setup both with vim and neovim, on NixOS and archlinux.

**Comment by hududed** [comment]
My bad, after a restart this is solved.
